# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x03pa1\"B\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\r.pa1.Category\"`\n\x0cOrderRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\"\n\norder_type\x18\x02 \x01(\x0e\x32\x0e.pa1.OrderType\x12\x18\n\x05items\x18\x03 \x03(\x0b\x32\t.pa1.Item\")\n\nOrderReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*M\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rGROCERY_ORDER\x10\x01\x12\x11\n\rRESTOCK_ORDER\x10\x02*\\\n\x08\x43\x61tegory\x12\x18\n\x14\x43\x41TEGORY_UNSPECIFIED\x10\x00\x12\t\n\x05\x42READ\x10\x01\x12\t\n\x05\x44\x41IRY\x10\x02\x12\x08\n\x04MEAT\x10\x03\x12\x0b\n\x07PRODUCE\x10\x04\x12\t\n\x05PARTY\x10\x05\x32?\n\tInventory\x12\x32\n\x0cProcessOrder\x12\x11.pa1.OrderRequest\x1a\x0f.pa1.OrderReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERTYPE']._serialized_start=233
  _globals['_ORDERTYPE']._serialized_end=310
  _globals['_CATEGORY']._serialized_start=312
  _globals['_CATEGORY']._serialized_end=404
  _globals['_ITEM']._serialized_start=24
  _globals['_ITEM']._serialized_end=90
  _globals['_ORDERREQUEST']._serialized_start=92
  _globals['_ORDERREQUEST']._serialized_end=188
  _globals['_ORDERREPLY']._serialized_start=190
  _globals['_ORDERREPLY']._serialized_end=231
  _globals['_INVENTORY']._serialized_start=406
  _globals['_INVENTORY']._serialized_end=469
# @@protoc_insertion_point(module_scope)
