# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AnalyticsEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AnalyticsEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAnalyticsEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AnalyticsEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AnalyticsEvent
    def EventId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AnalyticsEvent
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AnalyticsEvent
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AnalyticsEvent
    def TimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # AnalyticsEvent
    def LatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # AnalyticsEvent
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def AnalyticsEventStart(builder):
    builder.StartObject(6)

def Start(builder):
    AnalyticsEventStart(builder)

def AnalyticsEventAddEventId(builder, eventId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventId), 0)

def AddEventId(builder, eventId):
    AnalyticsEventAddEventId(builder, eventId)

def AnalyticsEventAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    AnalyticsEventAddSource(builder, source)

def AnalyticsEventAddEventType(builder, eventType):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(eventType), 0)

def AddEventType(builder, eventType):
    AnalyticsEventAddEventType(builder, eventType)

def AnalyticsEventAddTimestampMs(builder, timestampMs):
    builder.PrependInt64Slot(3, timestampMs, 0)

def AddTimestampMs(builder, timestampMs):
    AnalyticsEventAddTimestampMs(builder, timestampMs)

def AnalyticsEventAddLatencyMs(builder, latencyMs):
    builder.PrependFloat64Slot(4, latencyMs, 0.0)

def AddLatencyMs(builder, latencyMs):
    AnalyticsEventAddLatencyMs(builder, latencyMs)

def AnalyticsEventAddSuccess(builder, success):
    builder.PrependBoolSlot(5, success, 0)

def AddSuccess(builder, success):
    AnalyticsEventAddSuccess(builder, success)

def AnalyticsEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return AnalyticsEventEnd(builder)
