# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ItemQty(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ItemQty()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsItemQty(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ItemQty
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ItemQty
    def Item(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ItemQty
    def Qty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ItemQtyStart(builder):
    builder.StartObject(2)

def Start(builder):
    ItemQtyStart(builder)

def ItemQtyAddItem(builder, item):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(item), 0)

def AddItem(builder, item):
    ItemQtyAddItem(builder, item)

def ItemQtyAddQty(builder, qty):
    builder.PrependFloat64Slot(1, qty, 0.0)

def AddQty(builder, qty):
    ItemQtyAddQty(builder, qty)

def ItemQtyEnd(builder):
    return builder.EndObject()

def End(builder):
    return ItemQtyEnd(builder)
