# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RestockTask(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RestockTask()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRestockTask(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RestockTask
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RestockTask
    def TaskId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RestockTask
    def TaskType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RestockTask
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .ItemQty import ItemQty
            obj = ItemQty()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RestockTask
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RestockTask
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RestockTask
    def TimestampMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def RestockTaskStart(builder):
    builder.StartObject(4)

def Start(builder):
    RestockTaskStart(builder)

def RestockTaskAddTaskId(builder, taskId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(taskId), 0)

def AddTaskId(builder, taskId):
    RestockTaskAddTaskId(builder, taskId)

def RestockTaskAddTaskType(builder, taskType):
    builder.PrependInt8Slot(1, taskType, 0)

def AddTaskType(builder, taskType):
    RestockTaskAddTaskType(builder, taskType)

def RestockTaskAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    RestockTaskAddItems(builder, items)

def RestockTaskStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return RestockTaskStartItemsVector(builder, numElems)

def RestockTaskAddTimestampMs(builder, timestampMs):
    builder.PrependInt64Slot(3, timestampMs, 0)

def AddTimestampMs(builder, timestampMs):
    RestockTaskAddTimestampMs(builder, timestampMs)

def RestockTaskEnd(builder):
    return builder.EndObject()

def End(builder):
    return RestockTaskEnd(builder)
